#:kivy 2.3.0

<EstudiantesTab>:
    md_bg_color: self.theme_cls.backgroundColor

    MDBoxLayout:
        orientation: 'vertical'

        # 1. BARRA SUPERIOR
        MDTopAppBar:
            type: "small"
            
            MDTopAppBarTitle:
                text: "Directorio de Estudiantes"
                
            MDTopAppBarTrailingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "plus"
                    on_release: root.abrir_dialogo_agregar()
                MDActionTopAppBarButton:
                    icon: "reload"
                    on_release: root.cargar_estudiantes()

        # 2. BARRA DE BÚSQUEDA (Nueva sintaxis M3)
        MDBoxLayout:
            padding: dp(16), dp(8), dp(16), dp(8)
            size_hint_y: None
            height: dp(68)
            
            MDTextField:
                mode: "outlined"
                on_text: root.filtrar_estudiantes(self.text)
                
                MDTextFieldLeadingIcon:
                    icon: "magnify"
                    
                MDTextFieldHintText:
                    text: "Buscar por cédula o apellido..."

        # 3. ÁREA DE MENSAJES
        MDLabel:
            id: lbl_mensaje
            text: ""
            halign: "center"
            font_style: "Body"
            role: "medium"
            size_hint_y: None
            height: dp(0)
            theme_text_color: "Custom"
            text_color: (1, 0, 0, 1)

        # 4. LISTA DE ESTUDIANTES
        MDScrollView:
            MDList:
                id: lista_estudiantes
                padding: dp(10)
                spacing: dp(10)