#:kivy 2.3.0

<MateriasTab>:
    md_bg_color: self.theme_cls.backgroundColor

    MDBoxLayout:
        orientation: 'vertical'

        # 1. BARRA SUPERIOR
        MDTopAppBar:
            type: "small"
            
            MDTopAppBarTitle:
                text: "Mis Materias"
                
            MDTopAppBarTrailingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "plus"
                    on_release: root.abrir_dialogo_agregar()
                MDActionTopAppBarButton:
                    icon: "reload"
                    on_release: root.cargar_materias()

        # 2. ÁREA DE MENSAJES
        MDLabel:
            id: lbl_mensaje
            text: ""
            halign: "center"
            font_style: "Body"
            role: "medium"
            size_hint_y: None
            height: dp(0)
            theme_text_color: "Custom"
            text_color: (1, 0, 0, 1)

        # 3. LISTA DE MATERIAS
        MDScrollView:
            MDList:
                id: lista_materias
                padding: dp(10)
                spacing: dp(10)